import 'package:flutter/material.dart';
import '../services/supabase_service.dart';
import '../zenex_ui.dart';

class AchievementsPage extends StatefulWidget{const AchievementsPage({super.key});@override State<AchievementsPage>createState()=>_AchievementsPageState();}
class _AchievementsPageState extends State<AchievementsPage>{late Future<UserAnalytics>future;@override void initState(){super.initState();future=SupabaseService.analytics();}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Level & Achievements')),body:FutureBuilder<UserAnalytics>(future:future,builder:(_,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(s.hasError)return Center(child:Text('${s.error}'));final a=s.data!;final level=a.approved>=100?5:a.approved>=50?4:a.approved>=25?3:a.approved>=10?2:1;final next=level==1?10:level==2?25:level==3?50:level==4?100:100;final progress=level==5?1.0:(a.approved/next).clamp(0.0,1.0);final badges=[_Badge('First Step','Complete your first approved task.',a.approved>=1,Icons.flag_rounded),_Badge('Task Hunter','Reach 10 approved tasks.',a.approved>=10,Icons.search_rounded),_Badge('Rising Star','Reach 25 approved tasks.',a.approved>=25,Icons.auto_awesome_rounded),_Badge('Pro Worker','Reach 50 approved tasks.',a.approved>=50,Icons.workspace_premium_rounded),_Badge('Elite','Reach 100 approved tasks.',a.approved>=100,Icons.military_tech_rounded),_Badge('7-Day Fire','Maintain a 7-day activity streak.',a.streak>=7,Icons.local_fire_department_rounded)];return ListView(padding:const EdgeInsets.fromLTRB(16,8,16,30),children:[Container(padding:const EdgeInsets.all(21),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF386BFF),Color(0xFF7C3AED)]),borderRadius:BorderRadius.circular(26)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Icon(Icons.workspace_premium_rounded,color:Colors.white,size:30),const SizedBox(width:11),Text('LEVEL $level',style:const TextStyle(color:Colors.white,fontSize:22,fontWeight:FontWeight.w900))]),const SizedBox(height:9),Text(level==5?'Maximum milestone reached':'${a.approved} approved • next milestone $next',style:const TextStyle(color:Colors.white70)),const SizedBox(height:14),ClipRRect(borderRadius:BorderRadius.circular(20),child:LinearProgressIndicator(value:progress,minHeight:9,backgroundColor:Colors.white24,valueColor:const AlwaysStoppedAnimation<Color>(Colors.white)))]),const SizedBox(height:24),const SectionHeader(title:'Achievements',subtitle:'Keep completing quality work to unlock more'),const SizedBox(height:12),...badges.map((b)=>Padding(padding:const EdgeInsets.only(bottom:10),child:GlassCard(child:Row(children:[IconTile(b.icon,color:b.unlocked?kCyan:Colors.grey),const SizedBox(width:13),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(b.title,style:const TextStyle(fontWeight:FontWeight.w900)),const SizedBox(height:4),Text(b.description,style:const TextStyle(color:Colors.grey,fontSize:11))])),Icon(b.unlocked?Icons.check_circle_rounded:Icons.lock_outline_rounded,color:b.unlocked?kCyan:Colors.grey)]))))]));});}
}
class _Badge{final String title,description;final bool unlocked;final IconData icon;const _Badge(this.title,this.description,this.unlocked,this.icon);}
