import 'package:flutter/material.dart';
import '../services/supabase_service.dart';
import '../zenex_ui.dart';

class AnalyticsPage extends StatefulWidget{const AnalyticsPage({super.key});@override State<AnalyticsPage>createState()=>_AnalyticsPageState();}
class _AnalyticsPageState extends State<AnalyticsPage>{late Future<UserAnalytics> future;@override void initState(){super.initState();future=SupabaseService.analytics();}Future<void>refresh()async{setState(()=>future=SupabaseService.analytics());await future;}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Earnings Analytics'),actions:[IconButton(onPressed:refresh,icon:const Icon(Icons.refresh_rounded))]),body:FutureBuilder<UserAnalytics>(future:future,builder:(_,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(s.hasError)return EmptyState(icon:Icons.analytics_outlined,title:'Analytics unavailable',message:'${s.error}',onRetry:refresh);final a=s.data!;return RefreshIndicator(onRefresh:refresh,child:ListView(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.fromLTRB(16,8,16,30),children:[Row(children:[_Metric('Total earned','৳${zenexMoney(a.totalEarned)}',Icons.trending_up_rounded),const SizedBox(width:10),_Metric('This month','৳${zenexMoney(a.monthEarned)}',Icons.calendar_month_rounded)]),const SizedBox(height:10),Row(children:[_Metric('Approved','${a.approved}',Icons.check_circle_rounded),const SizedBox(width:10),_Metric('Streak','${a.streak} days',Icons.local_fire_department_rounded)]),const SizedBox(height:24),const SectionHeader(title:'Earnings trend',subtitle:'Approved rewards from the last 7 days'),const SizedBox(height:12),GlassCard(child:SizedBox(height:210,child:_BarChart(points:a.last7Days))),const SizedBox(height:24),const SectionHeader(title:'Task performance'),const SizedBox(height:12),GlassCard(padding:EdgeInsets.zero,child:Column(children:[_row('Approved',a.approved,Icons.check_circle_rounded,kCyan),const Divider(height:1),_row('Pending',a.pending,Icons.hourglass_top_rounded,Colors.amber),const Divider(height:1),_row('Rejected',a.rejected,Icons.cancel_rounded,Colors.pinkAccent),const Divider(height:1),_row('Screenshot submitted',a.screenshotSubmitted,Icons.photo_camera_outlined,kBlue)])),const SizedBox(height:24),const SectionHeader(title:'Money flow'),const SizedBox(height:12),GlassCard(padding:EdgeInsets.zero,child:Column(children:[_money('Earned',a.totalEarned,Icons.add_circle_outline_rounded,kCyan),const Divider(height:1),_money('Withdrawn',a.totalWithdrawn,Icons.remove_circle_outline_rounded,Colors.pinkAccent),const Divider(height:1),_money('Current balance',a.balance,Icons.account_balance_wallet_outlined,kBlue)]))]));}));}
}
class _Metric extends StatelessWidget{final String title,value;final IconData icon;const _Metric(this.title,this.value,this.icon);@override Widget build(BuildContext c)=>Expanded(child:GlassCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[IconTile(icon),const SizedBox(height:13),Text(value,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:3),Text(title,style:const TextStyle(fontSize:11,color:Colors.grey))])));}
Widget _row(String t,int v,IconData i,Color c)=>ListTile(leading:IconTile(i,color:c),title:Text(t,style:const TextStyle(fontWeight:FontWeight.w700,fontSize:13)),trailing:Text('$v',style:const TextStyle(fontWeight:FontWeight.w900,fontSize:17)));
Widget _money(String t,double v,IconData i,Color c)=>ListTile(leading:IconTile(i,color:c),title:Text(t,style:const TextStyle(fontWeight:FontWeight.w700,fontSize:13)),trailing:Text('৳${zenexMoney(v)}',style:const TextStyle(fontWeight:FontWeight.w900)));
class _BarChart extends StatelessWidget{final List<DailyPoint>points;const _BarChart({required this.points});@override Widget build(BuildContext c){double max=1;for(final p in points){if(p.amount>max)max=p.amount;}return Row(crossAxisAlignment:CrossAxisAlignment.end,children:points.map((p){final h=(p.amount/max)*145;return Expanded(child:Padding(padding:const EdgeInsets.symmetric(horizontal:4),child:Column(mainAxisAlignment:MainAxisAlignment.end,children:[Text(p.amount==0?'':'৳${p.amount.toStringAsFixed(0)}',style:const TextStyle(fontSize:9,color:Colors.grey)),const SizedBox(height:6),Container(height:h.clamp(4,145).toDouble(),decoration:BoxDecoration(gradient:const LinearGradient(begin:Alignment.topCenter,end:Alignment.bottomCenter,colors:[kCyan,kBlue]),borderRadius:BorderRadius.circular(8))),const SizedBox(height:7),Text(p.label,style:const TextStyle(fontSize:9,color:Colors.grey))]))).toList());}}
