import 'package:flutter/material.dart';
import '../services/supabase_service.dart';

class WalletPage extends StatefulWidget { const WalletPage({super.key}); @override State<WalletPage> createState()=>_WalletPageState(); }
class _WalletPageState extends State<WalletPage>{
  late Future<Map<String,dynamic>?> future; final amount=TextEditingController(); final account=TextEditingController(); String method='bkash'; bool busy=false;
  @override void initState(){super.initState();future=SupabaseService.wallet();}
  Future<void> withdraw()async{final a=double.tryParse(amount.text.trim());if(a==null||a<=0||account.text.trim().isEmpty){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Enter a valid amount and account number.')));return;}setState(()=>busy=true);try{await SupabaseService.withdraw(amount:a,method:method,account:account.text.trim());amount.clear();account.clear();setState(()=>future=SupabaseService.wallet());if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Withdrawal request submitted.')));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}finally{if(mounted)setState(()=>busy=false);}}
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Wallet')),body:RefreshIndicator(onRefresh:()async=>setState(()=>future=SupabaseService.wallet()),child:ListView(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.all(16),children:[
    FutureBuilder<Map<String,dynamic>?>(future:future,builder:(_,s){final b=s.data?['balance']??0;final e=s.data?['total_earned']??0;final w=s.data?['total_withdrawn']??0;return Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Available Balance'),const SizedBox(height:4),Text('৳ ${_money(b)}',style:const TextStyle(fontSize:32,fontWeight:FontWeight.w900)),const SizedBox(height:14),Row(children:[Expanded(child:Text('Earned ৳ ${_money(e)}')),Expanded(child:Text('Withdrawn ৳ ${_money(w)}'))])])));}),const SizedBox(height:16),
    Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Text('Request Withdrawal',style:TextStyle(fontSize:19,fontWeight:FontWeight.w800)),const SizedBox(height:14),DropdownButtonFormField<String>(value:method,decoration:const InputDecoration(labelText:'Payment method'),items:const[DropdownMenuItem(value:'bkash',child:Text('bKash')),DropdownMenuItem(value:'nagad',child:Text('Nagad')),DropdownMenuItem(value:'bank',child:Text('Bank'))],onChanged:(v)=>setState(()=>method=v!)),const SizedBox(height:12),TextField(controller:amount,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Amount (৳)')),const SizedBox(height:12),TextField(controller:account,keyboardType:TextInputType.phone,decoration:InputDecoration(labelText:method=='bank'?'Bank account number':'Mobile account number')),const SizedBox(height:14),SizedBox(height:50,child:FilledButton(onPressed:busy?null:withdraw,child:Text(busy?'Processing...':'Request withdrawal'))),const SizedBox(height:8),const Text('Minimum withdrawal is controlled by ZenexPay settings.',textAlign:TextAlign.center,style:TextStyle(color:Colors.grey))]))),
  ]));
}
String _money(dynamic v)=>(double.tryParse('$v')??0).toStringAsFixed(2);
